# Generated by Django 3.2.4 on 2021-06-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('No', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Design', models.CharField(max_length=100)),
                ('File', models.FileField(upload_to='files')),
            ],
        ),
    ]
