# Generated by Django 3.2.4 on 2021-06-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appshop', '0002_adminmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tot', models.IntegerField()),
            ],
        ),
    ]
