# Generated by Django 3.2.4 on 2021-06-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appshop', '0003_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminModel',
        ),
        migrations.DeleteModel(
            name='LoginModel',
        ),
        migrations.DeleteModel(
            name='RegisterModel',
        ),
        migrations.DeleteModel(
            name='Total',
        ),
        migrations.DeleteModel(
            name='TwitterModel',
        ),
    ]
